language: perl
perl:
    - "5.14"
    - "5.24"
install:
    - cpanm --quiet --notest List::Util Locale::Maketext::Test
    - cpanm Locale::Maketext
    - perl -MLocale::Maketext -e 'print $Locale::Maketext::VERSION';
