language: perl
perl:
    - "5.14"
    - "5.18.0"
    - "5.18.1"
    - "5.18.2"
    - "5.18.3"
    - "5.18.4"
    - "5.24"
install:
    - cpanm --quiet --notest List::Util Locale::Maketext::Test
    - perl -MLocale::Maketext -e 'print $Locale::Maketext::VERSION';
